export * from './tarefas.module';
export * from './shared';
export * from './listar';
export * from './cadastrar';
export * from './bebidas';
export * from './carne';
export * from './editar';
export * from './arroz';
export * from './tarefas-routing.module';
